{
 "title": "👩‍💻 CRA (auto)",
 "description": "크롤링 서버 (자동)",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "cra-server-1",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{host=\"ip-10-0-11-208\"} |= ``"
    }
   ]
  },
  {
   "title": "cra-server-2",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{host=\"ip-10-0-11-87\"} |= ``"
    }
   ]
  },
  {
   "title": "cra-server-3",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{host=\"ip-10-0-11-66\"} |= ``"
    }
   ]
  },
  {
   "title": "cra-server-4",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{host=\"ip-10-0-11-47\"} |= ``"
    }
   ]
  },
  {
   "title": "cra-server-5",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{host=\"ip-10-0-11-26\"} |= ``"
    }
   ]
  }
 ]
}