{
 "title": "👨‍💻 SLACKBOT",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "[Slackbot] 슬랙봇 전체 로그 확인",
   "type": "logs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container_name=\"slackbot_container\"} |= ``"
    }
   ]
  },
  {
   "title": "[Slackbot] 슬랙봇 에러 로그 확인",
   "type": "timeseries",
   "description": "에러 로그 확인",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{container_name=\"slackbot_container\"} |= `error`"
    }
   ]
  },
  {
   "title": "[Slackbot] 슬랙봇 경고(warn) 로그 확인",
   "type": "logs",
   "description": "warnings 로그 확인 가능합니다.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "{container_name=\"slackbot_container\"} |= `warn`"
    }
   ]
  }
 ]
}