apiVersion: 1 
datasources:
  - name: Loki
    type: loki
    access: proxy
    uid: loki
    orgId: 1
    url: http://loki:3100
    isDefault: false
    version: 1
    editable: false
    jsonData:
      timeout: 60
      maxLines: 1000